# When this name is defined it is exposed for interpolation and enviroment variable
# resolution as "COMPOSE_PROJECT_NAME"
name: "MCApp"

services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    networks:
      - wp-db-bridge
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER_NAME}
      - WORDPRESS_DB_PASSWORD=${MYSQL_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE_NAME}
    volumes:
      - web:/var/www/html
    networks:
      - wp-db-bridge
      - external-network
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 512m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  proxy:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - external-network
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-kf", "https://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    name: MCApp_data
  web:
    name: MCApp_web

networks:
  wp-db-bridge:
    driver: bridge
    internal: true
  external-network:
    driver: bridge
    internal: false


